/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtInPrinting: typeof import('./src/components/ArtInPrinting.vue')['default']
    Cover: typeof import('./src/components/Cover.vue')['default']
    PictorialComposition: typeof import('./src/components/PictorialComposition.vue')['default']
    PrintIconBook: typeof import('~icons/print-icon/book')['default']
    PrintPreview: typeof import('./src/components/PrintPreview.vue')['default']
  }
}
