<template>
  <section id="art-in-printing" class="chapter" data-chapter="1">
    <h1>Art in Printing</h1>

    <p>There is this vital difference between other objects of art and printing: That our  association with them is  purely voluntary, and that printing forces itself upon us at all times and in every relation of life. It is  impossible  for a person of intelligence to remove himself from the influence of printing. It confronts him at every  turn, and  in every relation of life it plays an important and insistent part.</p>
    <p>Such examples of art as a painting or a piece of statuary exert a certain influence upon a restricted number  of persons;  and it is at all times optional with all persons whether they submit themselves to the influence of such art  objects.  We are able to evade the influence of other forms of art, but we are not able to ward off printing. To it we  must  submit. It is constantly before our eyes; it is forever exerting its power upon our consciousness. It is  quite possible  that we may not at present be able to refer any quality of mind, or any degree of  cultivation, directly to printing, in any form it may have been presented to us; but it is easily  conceivable that printing  has a certain influence upon our esthetic life which has been so constant and so habitual as to have escaped  definite  recognition.</p>
    <p>If we engage our minds in some attempt to realize the quality and extent of pleasure and profit derivable  from the constant  influence of printing that conforms to artistic principles, we may perceive that it may be a most powerful  and effectual  agency for culture. It is understood that it is the gentle but constant influence that moulds our habits and  lives  the more readily and lastingly. If therefore it is possible for us to conceive that the printed page of a  book may  illustrate and enforce several of the more elemental and important principles underlying graphic art, we may  thereby  realize that printing may readily be employed in the character of a very powerful art educator, if because  of certain  inalienable limitations it must be denied full recognition as a member of the sisterhood of arts.</p>
    <p>The book page may be regarded as the protoplasm of all printing. If we examine the relation of principles of  art to the  book page we will be able to appreciate the exact importance of those principles in the composition of any  other form of printing, and to so apply them as to secure results most nearly relating printing to graphic  art.</p>
    <p>It is the chief characteristic of this uncertain dogma of art in printing that its limitations and variations  defy the  conventional forms of expression, and almost require a new vocabulary of art terms. It assuredly requires a  new and  a different comprehension of the terms of art, and a distinctly varied comprehension of the word art itself.  It has  ever been a stumbling block to printers that the word art as applied to their craft must be given a more  limited  significance than is given it in its usual acceptance. If we can come at some intelligible appreciation of  what we  mean by art in printing the way will be opened for the application of that motive to the work of the  presses.</p>
    <p>If we recognize at once the fact that we do not mean exactly what a painter means when we use the word art  with reference  to printing, we will have taken the vital step toward a comprehensible employment of the term, as well as  qualified  ourselves for an understanding of the results we desire to achieve.</p>
    <p>It is essential that we do not fall into the error of supposing that scientific accuracy is art. It is  destructive of  art, and the temptation to put too much stress upon exactitude is a mistake  the printer must guard himself from with the most sedulous care. It is agreeable to recognize the touch of  the artist, in  printing as in other arts, and scientific accuracy is certain to obliterate individuality. It is not the  cold, lifeless  abstraction, the shining exemplar of all the precepts and rules of art, that we love and desire, but the  human note  speaking through the principles and rules. If the artist is not the dominant note, and the rules submerged  by the  personality, there is no value in the object of art. The picture is interesting because the artist expresses  through  it his appreciation, his interpretation, of a beautiful thought or a lovely thing. This is what puts the  most faithful  photographs outside of the pale of art, and compels the idealization of the performance of the camera before  it can  be considered to be artistic. The photograph is not, usually, true to our view of life. If it is indeed true  to life  it represents a view of life that is quite strange to us, and often distasteful. We are not familiar with  the uncouth  animal the photograph shows us the horse in action to be, and we will not accept that caricature as the real  horse.  The horse that is real to us is the animal we see with our eyes, and the horse in art must be the animal we  see plus  the artist's logical idealization. The facts are the same with regard to nearly all of the  work of the camera, and with regard to other attempts at scientific accuracy in art. It is foreign to our  experience, and  does violence to our ideals. We actually see no such automatons as photography shows us men in action are,  and we  can never accept such disillusionment. If it is attempted in the name of art we will turn upon art and throw  it out  of our lives.</p>
  </section>
</template>
